name: Docker update description

on:
  push:
    branches: master
    paths:
      - README.md
      - .github/workflows/docker_update_desc.yml

env:
  # Image name at docker hub
  IMAGE_NAME: zinen2/alpine-pigpiod

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          repository: $IMAGE_NAME
